# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "examenes", :force => true do |t|
    t.column "metaexamen_id", :integer
    t.column "nombre",        :string
    t.column "supervisor",    :string
    t.column "respuestas",    :text
    t.column "fecha",         :date
  end

  create_table "metaexamenes", :force => true do |t|
    t.column "descriptor", :string
    t.column "campana",    :string
    t.column "rubro",      :string
    t.column "area",       :string
    t.column "preguntas",  :text
    t.column "tiempo",     :integer
  end

end
